### ISSUE TITLE
Select text and drag down.

### ISSUE THREAD

**Issue by ajwillia-ms** [Enlightenment/edi#14]
In Edi there are select inconsistencies.

Select text and drag up
Select continues;
Select text and drag down
Select will remain on the same view, unable to continue scrolling select. (ISSUE)

**Comment by ajwillia-ms** [comment]
This is a bug in elm_code (efl) but it should be relatively straight forward to fix.
The problem is that in a large selection the cursor remains at the beginning rather than at the end that the mouse is.

**Comment by haxworx** [comment]
I made a patch for this. Maybe it's not perfect, but let's see:

https://phab.enlightenment.org/D6632

**Comment by haxworx** [comment]
This is fixed and will be in efl-1.21
