### ISSUE TITLE
edi-0.7.0 compile error with efl-1.22.1

### ISSUE THREAD

**Issue by dulm-today** [Enlightenment/edi#25]
## Error info message:
`../src/bin/edi_consolepanel.c:387:35: error: ‘ELM_OBJ_CODE_WIDGET_EVENT_LINE_CLICKED’ undeclared (first use in this function)
    efl_event_callback_add(widget, ELM_OBJ_CODE_WIDGET_EVENT_LINE_CLICKED, _edi_consolepanel_clicked_cb, code);`

## Environment
* edi-0.7.0
* efl-1.22.1
* gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)
* Ubuntu 16.04.6 LTS

**Comment by andydotxyz** [comment]
It looks like that callback was renamed to EFL_UI_CODE_WIDGET_EVENT_LINE_CLICKED at some point. We need to do a patch release of Edi to accomodate.
It seems that this was changed for the 0.22 release so we are behind and should update.
I will look into this. It is possible that there may be additional issues once it compiles as the scroll behaviour has changed as well.

**Comment by andydotxyz** [comment]
This was already fixed in 847e488.
I’ll do some testing and we can release a 0.7.1 to address this for anyone who is not building from master
