### ISSUE TITLE
Multiple undefined symbol errors - compiling edi-0.6.0 on FreeBSD

### ISSUE THREAD

**Issue by a-bateman** [Enlightenment/edi#29]
Am working on getting a pkg ready for FreeBSD 12.1-RELEASE-p6 as I cannot find one in the ports tree/pkg.
  
Downloaded source from https://download.enlightenment.org/rel/apps/edi/
Using EFL 1.25.1_2.

Issues with linking multiple "elm_obj_code_widget_" symbols.
Fixed a previous compilation error by switching "obj" to "ui" but it does not seem to work in this situation.

Error messages:

` /usr/bin/install -c -m 644 edi_build_provider.h edi_builder.h edi_create.h edi_path.h edi_exe.h edi_scm.h Edi.h '/usr/local/include/edi-0'
Making install in bin
  CCLD     edi
ld: error: undefined symbol: elm_obj_code_widget_font_set
>>> referenced by edi_editor.c:1311 (editor/edi_editor.c:1311)
>>>               editor/edi_editor.o:(edi_editor_add)

ld: error: undefined symbol: elm_obj_code_widget_show_whitespace_set
>>> referenced by edi_editor.c:1312 (editor/edi_editor.c:1312)
>>>               editor/edi_editor.o:(edi_editor_add)

ld: error: undefined symbol: elm_obj_code_widget_tab_inserts_spaces_set
>>> referenced by edi_editor.c:1313 (editor/edi_editor.c:1313)
>>>               editor/edi_editor.o:(edi_editor_add)

ld: error: undefined symbol: elm_obj_code_widget_line_width_marker_set
>>> referenced by edi_editor.c:1314 (editor/edi_editor.c:1314)
>>>               editor/edi_editor.o:(edi_editor_add)

ld: error: undefined symbol: elm_obj_code_widget_tabstop_set
>>> referenced by edi_editor.c:1315 (editor/edi_editor.c:1315)
>>>               editor/edi_editor.o:(edi_editor_add)

ld: error: undefined symbol: elm_obj_code_widget_font_set
>>> referenced by edi_editor.c:1311 (editor/edi_editor.c:1311)
>>>               editor/edi_editor.o:(_edi_editor_config_changed)

ld: error: undefined symbol: elm_obj_code_widget_show_whitespace_set
>>> referenced by edi_editor.c:1312 (editor/edi_editor.c:1312)
>>>               editor/edi_editor.o:(_edi_editor_config_changed)

ld: error: undefined symbol: elm_obj_code_widget_tab_inserts_spaces_set
>>> referenced by edi_editor.c:1313 (editor/edi_editor.c:1313)
>>>               editor/edi_editor.o:(_edi_editor_config_changed)

ld: error: undefined symbol: elm_obj_code_widget_line_width_marker_set
>>> referenced by edi_editor.c:1314 (editor/edi_editor.c:1314)
>>>               editor/edi_editor.o:(_edi_editor_config_changed)

ld: error: undefined symbol: elm_obj_code_widget_tabstop_set
>>> referenced by edi_editor.c:1315 (editor/edi_editor.c:1315)
>>>               editor/edi_editor.o:(_edi_editor_config_changed)

ld: error: undefined symbol: elm_obj_code_widget_font_set
>>> referenced by edi_settings_font.c:40 (screens/edi_settings_font.c:40)
>>>               screens/edi_settings_font.o:(_cb_op_font_content_get)

ld: error: undefined symbol: elm_obj_code_widget_line_numbers_set
>>> referenced by edi_settings_font.c:41 (screens/edi_settings_font.c:41)
>>>               screens/edi_settings_font.o:(_cb_op_font_content_get)

ld: error: undefined symbol: elm_obj_code_widget_editable_set
>>> referenced by edi_settings_font.c:42 (screens/edi_settings_font.c:42)
>>>               screens/edi_settings_font.o:(_cb_op_font_content_get)

ld: error: undefined symbol: elm_obj_code_widget_policy_set
>>> referenced by edi_settings_font.c:43 (screens/edi_settings_font.c:43)
>>>               screens/edi_settings_font.o:(_cb_op_font_content_get)

ld: error: undefined symbol: elm_obj_code_widget_font_set
>>> referenced by edi_settings.c:133 (screens/edi_settings.c:133)
>>>               screens/edi_settings.o:(edi_settings_show)

ld: error: undefined symbol: elm_obj_code_widget_line_numbers_set
>>> referenced by edi_settings.c:134 (screens/edi_settings.c:134)
>>>               screens/edi_settings.o:(edi_settings_show)

ld: error: undefined symbol: elm_obj_code_widget_editable_set
>>> referenced by edi_settings.c:135 (screens/edi_settings.c:135)
>>>               screens/edi_settings.o:(edi_settings_show)

ld: error: undefined symbol: elm_obj_code_widget_policy_set
>>> referenced by edi_settings.c:136 (screens/edi_settings.c:136)
>>>               screens/edi_settings.o:(edi_settings_show)

ld: error: undefined symbol: elm_obj_code_widget_font_set
>>> referenced by edi_scm_screens.c:478 (screens/edi_scm_screens.c:478)
>>>               screens/edi_scm_screens.o:(edi_scm_screens_commit)

ld: error: undefined symbol: elm_obj_code_widget_gravity_set
>>> referenced by edi_scm_screens.c:479 (screens/edi_scm_screens.c:479)
>>>               screens/edi_scm_screens.o:(edi_scm_screens_commit)

ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1
`

**Comment by haxworx** [comment]
Ah yes that is Old.

Github has 0.8.0. Didn't update pkg here when src was moved back. Author
moved onto other things. See,

https://github.com/Enlightenment/edi/releases/download/v0.8.0/edi-0.8.0.tar.xz

I will try to remember to update the links etc.

**Comment by a-bateman** [comment]
Thank you.  I'm going to try to work through the issues I have with this build.  Thank you.
